Repository mandiant/capa-rules, pull requests merged in 2021-06, with the labels that each got.

#405 ci: fix rule counting in CHANGELOG
  .github/workflows/sync.yml
Labels: CI

#406 2021 06 04 graduation
  communication/http/client/create-bits-job.yml
  compiler/nim/compiled-with-nim.yml
  data-manipulation/encoding/base64/decode-data-using-base64-via-winapi.yml
  data-manipulation/encoding/base64/encode-data-using-base64-via-winapi.yml
  data-manipulation/hmac/authenticate-hmac.yml
  host-interaction/file-system/meta/get-file-size.yml
  host-interaction/file-system/meta/get-file-version-info.yml
  host-interaction/gui/console/set-console-window-title.yml
  host-interaction/process/modify/acquire-debug-privileges.yml
  host-interaction/wmi/connect-to-wmi-namespace-via-wbemlocator.yml
  nursery/compiled-from-epl.yml
Labels: enhancement

#407 tighten up parse credit card rule
  collection/credit-card/parse-credit-card-information.yml
Labels: false positive

#413 2021 06 08 graduation
  anti-analysis/anti-debugging/debugger-detection/check-processdebugport.yml
  data-manipulation/encryption/get-outbound-credentials-handle-via-credssp.yml
  data-manipulation/hashing/md5/hash-data-with-md5.yml
  host-interaction/environment-variable/get-comspec-environment-variable.yml
  host-interaction/file-system/move/move-file.yml
  host-interaction/file-system/read/read-file-via-mapping.yml
  host-interaction/session/get-token-membership.yml
  host-interaction/session/get-user-security-identifier.yml
  host-interaction/thread/list/enumerate-threads.yml
  host-interaction/uac/bypass/bypass-uac-via-icmluautil.yml
  lib/get-service-handle.yml
  nursery/hash-data-with-md5.yml
Labels: enhancement
