Repository mandiant/capa-rules, pull requests merged in 2021-05, with the labels that each got.

#341 ATT&CK v9 updates
  collection/acquire-credentials-from-windows-credential-manager.yml
  collection/get-geographical-location.yml
  collection/network/capture-public-ip.yml
  host-interaction/process/create/create-process.yml
  persistence/registry/persist-via-active-setup-registry-key.yml
Labels: att&ck

#376 adding check-internet-connectivity-via-wininet.yml
  host-interaction/network/connectivity/check-internet-connectivity-via-wininet.yml
  host-interaction/network/connectivity/get-internet-connection-state.yml
Labels: att&ck

#378 ci: support multiple author in sync GH
  .github/scripts/changelog_author.py
  .github/workflows/sync.yml
Labels: CI, bug

#381 ICMLuaUtil: fix logic, add description
  nursery/bypass-uac-via-icmluautil.yml
Labels: bug

#388 use descriptions instead of inline comments
  anti-analysis/anti-forensic/self-deletion/self-delete-via-comspec-environment-variable.yml
  collection/screenshot/capture-screenshot.yml
  communication/http/client/get-http-document-via-iwebbrowser2.yml
  communication/http/initialize-iwebbrowser2.yml
  communication/http/server/receive-http-request.yml
  communication/named-pipe/connect/connect-pipe.yml
  communication/named-pipe/read/read-pipe.yml
  communication/named-pipe/write/write-pipe.yml
  compiler/autoit/compiled-with-autoit.yml
  compiler/mingw/compiled-with-mingw-for-windows.yml
  data-manipulation/checksum/adler32/compute-adler32-checksum.yml
  data-manipulation/compression/decompress-data-using-aplib.yml
  data-manipulation/encoding/base64/encode-data-using-base64.yml
  data-manipulation/encoding/xor/encode-data-using-xor.yml
  data-manipulation/encryption/aes/decrypt-data-using-aes-via-x86-extensions.yml
  data-manipulation/encryption/rc6/encrypt-data-using-rc6.yml
  data-manipulation/hashing/fnv/hash-data-using-fnv.yml
  data-manipulation/hashing/sha1/hash-data-using-sha1.yml
  host-interaction/file-system/windows-file-protection/bypass-windows-file-protection.yml
  host-interaction/process/create/create-a-process-with-modified-io-handles-and-window.yml
  impact/wipe-disk/wipe-mbr/overwrite-master-boot-record-mbr.yml
  linking/runtime-linking/access-peb-ldr_data.yml
  linking/runtime-linking/resolve-function-by-fin8-fasthash.yml
  load-code/pe/rebuild-import-table.yml
  nursery/encrypt-data-using-aes-via-x86-extensions.yml
  nursery/encrypt-data-using-salsa20-or-chacha.yml
  nursery/enumerate-browser-history.yml
  nursery/flush-cabinet-file.yml
  nursery/get-file-version-info.yml
  nursery/hash-data-using-sha1-via-x86-extensions.yml
  nursery/hash-data-using-sha256-via-x86-extensions.yml
  nursery/hash-data-with-md5.yml
  nursery/linked-against-c-regex-library.yml
  nursery/reference-processor-manufacturer-constants.yml
  targeting/automated-teller-machine/diebold-nixdorf/reference-diebold-atm-routines.yml
  targeting/automated-teller-machine/identify-atm-dispenser-service-provider.yml
  targeting/automated-teller-machine/ncr/load-ncr-atm-library.yml
Labels: enhancement

#399 format: document function-name feature
  doc/format.md
Labels: enhancement
