Repository mandiant/capa-rules, pull requests merged in 2023-01, with the labels that each got.

#647 add "execute via .NET startup hook"
  runtime/dotnet/execute-via-dotnet-startup-hook.yml
Labels: enhancement

#649 tests: better detect rule name
  .github/workflows/tests.yml
Labels: bug

#652 add compiled-with-nuitka
  compiler/nuitka/compiled-with-nuitka.yml
Labels: enhancement

#653 add authenticate data with md5 mac
  nursery/authenticate-data-with-md5-mac.yml
Labels: enhancement

#657 more SHA1 constants
  data-manipulation/hashing/sha1/hash-data-using-sha1.yml
Labels: enhancement

#658 sha* rules and updates
  data-manipulation/hashing/sha224/hash-data-using-sha224.yml
  data-manipulation/hashing/sha256/hash-data-using-sha256.yml
  data-manipulation/hashing/sha384/hash-data-using-sha384.yml
  data-manipulation/hashing/sha512/hash-data-using-sha512.yml
Labels: enhancement

#660 add weekly scheduled run of lint --thorough
  .github/workflows/tests.yml
Labels: CI

#666 rc5/6: more constants
  data-manipulation/encryption/rc6/encrypt-data-using-rc6.yml
Labels: enhancement

#667 add TEA encryption
  nursery/decrypt-data-using-tea.yml
  nursery/encrypt-data-using-tea.yml
Labels: enhancement

#665 add whirlpool hash
  nursery/hash-data-using-whirlpool.yml
Labels: enhancement

#669 add base58
  nursery/reference-base58-string.yml
Labels: enhancement

#672 des: add more constants from libtomcrypt
  data-manipulation/encryption/des/encrypt-data-using-des.yml
Labels: enhancement

#673 add create-mailslot
  communication/mailslot/create-mailslot.yml
Labels: enhancement
